# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 840a1f1b771db49a1263f731baf28fba5ba5e4a8e128595e1bd9cb0ef36bbac552284675ff3db4e15301fb581a454db76dc5b9940b1bec3318919c69d3a28c8e

test:
  secret_key_base: ff65e449956ea47f355a4ecb103021baa28911d377d755d7fa4c98989aaadcc79e49dffd8bedfa07e2917ed46a97ff5fad078bb24751c8fcef65ae1980e9614b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
